# Generated by Django 5.1.4 on 2025-01-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=40)),
                ('Contact_No', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
