# Generated by Django 5.1.4 on 2025-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='MRnumber',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
