# Generated by Django 5.1.4 on 2025-03-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0002_patient_mrnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='hospital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.hospital'),
        ),
    ]
