# Generated by Django 5.1.4 on 2025-03-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0003_ambulance_hospital_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('amb_login_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulancs', to='imfnapp.ambulance')),
                ('pat_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='imfnapp.patient')),
            ],
        ),
    ]
