# Generated by Django 5.1.4 on 2025-01-31 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0005_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.login'),
        ),
    ]
