# Generated by Django 5.1.4 on 2025-03-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0006_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='hosp_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosps', to='imfnapp.hospital'),
        ),
    ]
