# Generated by Django 5.1.4 on 2025-02-10 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0006_patient_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=25)),
                ('photo', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('DOB', models.DateField(max_length=25)),
                ('specialisation', models.CharField(max_length=40)),
                ('year_of_experience', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=15)),
                ('hospital_name', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.hospital')),
                ('loginid', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.login')),
            ],
        ),
    ]
