# Generated by Django 5.1.4 on 2025-02-01 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0007_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.login'),
        ),
    ]
