# Generated by Django 5.1.4 on 2025-02-10 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0007_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imfnapp.hospital'),
        ),
    ]
