# Generated by Django 5.1.4 on 2025-03-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0007_location_hosp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_category', models.CharField(max_length=35)),
                ('company_name', models.CharField(max_length=45)),
                ('medicine_name', models.CharField(max_length=45)),
                ('medicine_details', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
