# Generated by Django 5.1.4 on 2025-03-17 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0008_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='transferpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('from_hospital', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospi', to='imfnapp.hospital')),
                ('pat_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='pat', to='imfnapp.patient')),
                ('to_hospital', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospit', to='imfnapp.hospital')),
            ],
        ),
    ]
