# Generated by Django 5.1.4 on 2025-03-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0010_medicines_pharmacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='medicine_details',
            field=models.CharField(max_length=80),
        ),
    ]
