# Generated by Django 5.1.4 on 2025-03-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0011_alter_medicines_medicine_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='hos_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='hos', to='imfnapp.hospital'),
        ),
    ]
