# Generated by Django 5.1.4 on 2025-02-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0011_remove_doctor_login_id_doctor_loginid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='loginid',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Login_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.login'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(max_length=40),
        ),
    ]
