# Generated by Django 5.1.4 on 2025-03-24 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0012_pharmacy_hos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital_login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_login', to='imfnapp.hospital'),
        ),
    ]
