# Generated by Django 5.1.4 on 2025-02-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0012_remove_doctor_loginid_doctor_login_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
