# Generated by Django 5.1.4 on 2025-03-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0013_alter_doctor_hospital_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
