# Generated by Django 5.1.4 on 2025-02-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0013_alter_doctor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Login_id',
        ),
    ]
