# Generated by Django 5.1.4 on 2025-02-17 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0014_remove_doctor_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Login_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.login'),
        ),
    ]
