# Generated by Django 5.1.4 on 2025-04-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0014_appointment_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='Contact_No',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Contact_No',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
