# Generated by Django 5.1.4 on 2025-04-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0015_alter_ambulance_contact_no_alter_doctor_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='complete_status',
            field=models.IntegerField(default=0),
        ),
    ]
