# Generated by Django 5.1.4 on 2025-04-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0016_location_complete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True, null=True)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('patt_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='patent', to='imfnapp.patient')),
            ],
        ),
    ]
