# Generated by Django 5.1.4 on 2025-02-17 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0016_remove_doctor_login_id_doctor_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Hospital_Name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.hospital'),
        ),
    ]
