# Generated by Django 5.1.4 on 2025-04-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0017_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='xray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray_file', models.FileField(blank=True, null=True, upload_to='xray_files/')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pati', to='imfnapp.patient')),
            ],
        ),
    ]
