# Generated by Django 5.1.4 on 2025-02-19 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0017_remove_doctor_hospital_name_doctor_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Hospital_Name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.hospital'),
        ),
    ]
