# Generated by Django 5.1.4 on 2025-02-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0018_remove_doctor_hospital_name_doctor_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Login_id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_name',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.login'),
        ),
    ]
