# Generated by Django 5.1.4 on 2025-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0018_xray'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti', models.TextField(blank=True, null=True)),
                ('current_dates', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
