# Generated by Django 5.1.4 on 2025-02-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0019_remove_doctor_login_id_alter_doctor_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='login_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_login', to='imfnapp.login'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_name',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_hospital', to='imfnapp.hospital'),
        ),
    ]
