# Generated by Django 5.1.4 on 2025-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferpatient',
            name='records',
            field=models.FileField(blank=True, null=True, upload_to='xray_files/'),
        ),
    ]
