# Generated by Django 5.1.4 on 2025-02-19 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0020_doctor_login_id_alter_doctor_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_login_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_login', to='imfnapp.login'),
            preserve_default=False,
        ),
    ]
