# Generated by Django 5.1.4 on 2025-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0020_transferpatient_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferpatient',
            name='records',
            field=models.TextField(blank=True, null=True),
        ),
    ]
