# Generated by Django 5.1.4 on 2025-02-19 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0021_remove_doctor_hospital_name_doctor_hospital_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(max_length=25)),
                ('Time', models.TimeField(max_length=25)),
                ('Current_Date', models.DateField(auto_now_add=True)),
                ('Payment_Status', models.IntegerField(default=0)),
                ('doctor_login_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='imfnapp.login')),
                ('patient_login_id', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_login', to='imfnapp.login')),
            ],
        ),
    ]
