# Generated by Django 5.1.4 on 2025-05-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0021_alter_transferpatient_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferpatient',
            name='records',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
