# Generated by Django 5.1.4 on 2025-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0022_alter_transferpatient_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='availability_status',
            field=models.IntegerField(default=0),
        ),
    ]
