# Generated by Django 5.1.4 on 2025-02-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0023_payment_alter_appointment_doctor_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_login_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='imfnapp.login'),
        ),
    ]
