# Generated by Django 5.1.4 on 2025-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0023_ambulance_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected')], default=2),
        ),
    ]
