# Generated by Django 5.1.4 on 2025-02-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0024_alter_appointment_doctor_login_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
