# Generated by Django 5.1.4 on 2025-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0024_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
