# Generated by Django 5.1.4 on 2025-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0025_alter_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='availability_status',
            field=models.IntegerField(default=1),
        ),
    ]
