# Generated by Django 5.1.4 on 2025-02-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0025_delete_payment_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DOB',
            field=models.DateField(),
        ),
    ]
