# Generated by Django 5.1.4 on 2025-02-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0027_alter_doctor_hospital_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Current_Date', models.DateField(auto_now_add=True)),
                ('Card_owner', models.CharField(max_length=25)),
                ('Card_no', models.CharField(max_length=16)),
                ('Exp_month', models.IntegerField()),
                ('Exp_year', models.IntegerField()),
                ('CVV', models.CharField(max_length=4)),
            ],
        ),
    ]
