# Generated by Django 5.1.4 on 2025-02-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0015_doctor_login_id'),
        ('imfnapp', '0028_payment'),
    ]

    operations = [
    ]
