# Generated by Django 5.1.4 on 2025-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0028_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
