# Generated by Django 5.1.4 on 2025-02-26 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0029_alter_doctor_consultation_fee_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Login_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imfnapp.login'),
        ),
    ]
