# Generated by Django 5.1.4 on 2025-02-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0029_merge_0015_doctor_login_id_0028_payment'),
        ('imfnapp', '0030_alter_patient_login_id'),
    ]

    operations = [
    ]
