# Generated by Django 5.1.4 on 2025-02-28 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0031_appointment_cancel_status_alter_patient_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_login_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors_logins', to='imfnapp.login'),
        ),
    ]
