# Generated by Django 5.1.4 on 2025-03-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imfnapp', '0033_alter_appointment_doctor_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
